service: auth-service
frameworkVersion: '3'

custom:
  secrets: ${file(secrets.json)}

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  environment:
    JWT_SECRET: ${self:custom.secrets.JWT_SECRET}
    DB: ${self:custom.secrets.DB}

functions:
  verifyToken:
    handler: src/handler/verify-token.handler

  login:
    handler: src/handler/login.handler
    events:
      - http:
          path: login
          method: post
          cors: true

  register:
    handler: src/handler/register.handler
    events:
      - http:
          path: register
          method: post
          cors: true

  me:
    handler: src/handler/me.handler
    events:
      - http:
          path: me
          method: get
          cors: true
          authorizer: verifyToken

  getUsers:
    handler: src/handler/get-users.handler
    events:
      - http:
          path: users
          method: get
          cors: true

plugins:
  - serverless-offline